Lss commit SmartScheduling
Jack47/hack-SysML pull request #8
Opened 2022-06-15 15:23 UTC by La-campanella

md里只对smart_scheduling.h进行了解读，其他两个源码的注释解读，写的比较乱，等周末没课了，再进行总结。

2022-06-15 23:22 UTC, Jack47 requested changes

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +        cudaStream_t stream, ncclComm_t comm) {
下面的函数都是异步的，即CPU执行后会发射kernel，让 GPU 去做。后面会查询是否做完了

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +        ncclSend(sendbuf, sendcount * d_model * sizeof(scalar_t),
ncclSend是点对点的通信，比如这里是说发给  t_send 这个序号的人数据

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +                exchangeWith(input_buf + local_ptr[idx_send] * d_model,
虽然通过for循环嵌套来进行了 n_groups*num_experts 次 exchangeWith，但由于都是用的 ncclcomm 这同一个 stream，所以通信过程是串行的。而其他这里涉及到的计算是在CPU上做的，所以和通信是并行的

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +    // Broadcast shadowed experts(将影子专家进行广播，这是论文中对负载不均衡的改进)
广播这一部分可以先不管

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +            NCCL_SAFE_CALL(ncclGroupStart());
ncclGroupStart时，不需要指定有哪些人参与到这个group里？难道默认是所有人都在

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +        cudaEventRecord(input_ready[step], smgr->stream(0));
为什么是step粒度的记录，而非更细粒度ei粒度的

2022-06-15 23:22 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +        for (long ei = 0; ei < num_expert; ++ei) {
这里的ei没明白是啥意思？当前代码是在k这个人上执行的，那它需要与其他人进行通信，所以ei就是其他人的意思。每次exchange都是说(k, ei) 进行通信

2022-06-15 23:22 UTC, Jack47 commented on map.md
> -
这些不需要修改

2022-06-17 07:15 UTC, La-campanella commented on papers/fasterMoe/SmartScheduling.md
> +            NCCL_SAFE_CALL(ncclGroupStart());
栋哥我的理解是这样的：每一个组有不同的worker，前面的step相当于指定了哪个组(因为这里组数和需要进行的all-to-all信息交流的次数是相同的)，然后根据GEN_BASE和GEN_IDX两个宏替换，来得知需要进行发送和接收的数据来自哪个组

2022-06-17 07:21 UTC, La-campanella commented on papers/fasterMoe/SmartScheduling.md
> +        for (long ei = 0; ei < num_expert; ++ei) {
作者对于num_expert的解释为：`num_expert` stands for the number of experts on **each** worker.
在说明中指定了fastermoe中num_expert必需设为1(作者说功能还没完善，所以源码这里默认都为1)

2022-06-17 08:31 UTC, La-campanella commented on papers/fasterMoe/SmartScheduling.md
> +        cudaEventRecord(input_ready[step], smgr->stream(0));
粒度的划分是这样的：以前S,C,R操作都是串行的，比如S1,C1,R1然后再S2,C2,R1这种串行，现在将S,C,R操作给切分了，这时候为了最小化延迟将woker分组，是以组进行通信交流的，这个Record是写在有关S,C的循环里的。

2022-06-17 09:10 UTC, La-campanella commented
栋哥我又看了下源代码捋了一遍，感觉fmoe_cuda_fused_forward_impl是针对一个worker的信息收发与计算，其中有rank字段，代表了是所有worker序号的哪一个worker

2022-06-19 22:44 UTC, merged

2022-06-19 22:44 UTC, Jack47 approved these changes

2022-06-19 22:44 UTC, Jack47 commented on papers/fasterMoe/SmartScheduling.md
> +        py::function forward_fn,
forward_fn 有没有看一下，最上层是python的，这里是c++版本的，是如何转换的？